In [1]:
#accessing netcdf files from Hector's folders
import os, glob, sys
sys.path.append("//nobackup//amondal//Python//Hector_Python_Scripts")
sys.path.append("//nobackup/amondal//Python//mit_geos_analysis")
#playing with netcdf - xarray
import numpy as np
import xarray as xr
import dask.array as da
import matplotlib.pyplot as plt
import dask_ndfilters
# How about visualization?
%matplotlib inline
from xmovie import Movie
import xrscipy.signal as dsp
import xrft
import scipy.signal as scp
import netCDF4
import xgcm
from netCDF4 import Dataset
import time as tm
from xmitgcm import open_mdsdataset
import time as tm
import pylab as plt
from llcmap_bi_split import LLCMap_bi_split
from face_connections import face_connections
from llcmap_nea_split import LLCMap_nea_split
from timeline_MITgcm import timeline
from datetime import datetime, timedelta
import importlib
from GetNCDataSet import getMITNCDataSet
from MIT_xr_cwt_dateloc_fol import loadMITData
from MITllc2160Depth import *


from dask.distributed import Client
client = Client(memory_limit='90GB',n_workers = 40, threads_per_worker=1)

In [2]:
# good - now, let me make a bunch of .nc files:
fol = "/nobackup/amondal/NCData/20211004_NoAt_GulfStream_April_Test/"
VAR = "Zeta"
firstlevel = 0
finallevel = 1
Zeta = getMITNCDataSet(fol,VAR, firstlevel,finallevel)
fol2 = "/nobackup/amondal/Zeta_loadMITDatatest_April"
Zeta_comp = getMITNCDataSet(fol, VAR, firstlevel, finallevel)

Time combined dataset has been opened.
I concatenated the first Z-layer
Time combined dataset has been opened.
I concatenated the first Z-layer


In [3]:
y1 = 2020
y2 = 2020
m1 = 3
m2 = 3
d1 = 1
d2 = 1
h1 = 0
h2 = 2
M1 = 0
M2 = 0

lat1 = 34
lat2 = 35
latinc = 0.04
lon1 = -65
lon2 = -64
loninc = 0.04

levels=0
ffilter=0
fsize=0
zeta = loadMITData('Zeta', levels, ffilter, fsize, y1, m1, d1, h1 ,M1, y2, m2, d2, h2, M2, lat1, lat2, latinc, lon1, lon2, loninc)

Entering MIT_xr_date_location
date
[datetime.datetime(2020, 3, 1, 0, 0) datetime.datetime(2020, 3, 1, 1, 0)
 datetime.datetime(2020, 3, 1, 2, 0)]

[78880. 78960. 79040.]

setting location
location
Directory of files
/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/oceTAUX
before mds
grid xgcm.Grid
initialize mapping to GEOS grid
0
open files
78880.0
=== x interpolated  ==
nan
map field
mapped
finished day 00
1
open files
78960.0
=== x interpolated  ==
nan
map field
mapped
finished day 01
2
open files
79040.0
=== x interpolated  ==
nan
map field
mapped
finished day 02


In [4]:
fol = "/nobackup/amondal/NCData/20210830_RegBal_5day/"
VAR = "Zeta"
firstlevel = 0
finallevel = 1
Zeta = getMITNCDataSet(fol,VAR, firstlevel,finallevel)

Time combined dataset has been opened.
I concatenated the first Z-layer


In [23]:
zeta

<xarray.DataArray 'Zeta' (time: 2, lat: 25, lon: 25)>
array([[[-4.94020895e-08, -1.50054476e-07, -2.76412550e-07, ...,
         -5.30357340e-08, -6.71140228e-08, -1.31372673e-07],
        [-1.08695055e-07, -2.18964217e-07, -3.26239501e-07, ...,
         -2.31690862e-08, -9.95435645e-09, -4.63364849e-08],
        [-1.38918111e-07, -2.78560435e-07, -4.29322228e-07, ...,
         -7.44508171e-08,  1.71842984e-08,  1.08504636e-07],
        ...,
        [-4.13379411e-07, -3.08904134e-07, -6.65230786e-08, ...,
          2.06776861e-07,  1.49885395e-07,  4.69794195e-08],
        [-5.07708478e-07, -4.51105279e-07, -3.87404469e-07, ...,
         -1.41683813e-07, -1.44274281e-07, -1.42474903e-07],
        [-7.89154853e-07, -7.79717425e-07, -8.32743126e-07, ...,
         -4.56432645e-07, -3.68406688e-07, -2.61230838e-07]],

       [[-4.94020895e-08, -1.50054476e-07, -2.76412550e-07, ...,
         -5.30357340e-08, -6.71140228e-08, -1.31372673e-07],
        [-1.08695055e-07, -2.18964217e-07, -3.26239501e-07, ...,
         -2.31690862e-08, -9.95435645e-09, -4.63364849e-08],
        [-1.38918111e-07, -2.78560435e-07, -4.29322228e-07, ...,
         -7.44508171e-08,  1.71842984e-08,  1.08504636e-07],
        ...,
        [-4.13379411e-07, -3.08904134e-07, -6.65230786e-08, ...,
          2.06776861e-07,  1.49885395e-07,  4.69794195e-08],
        [-5.07708478e-07, -4.51105279e-07, -3.87404469e-07, ...,
         -1.41683813e-07, -1.44274281e-07, -1.42474903e-07],
        [-7.89154853e-07, -7.79717425e-07, -8.32743126e-07, ...,
         -4.56432645e-07, -3.68406688e-07, -2.61230838e-07]]])
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04
Dimensions without coordinates: time

In [5]:
Zeta

<xarray.Dataset>
Dimensions:  (lat: 25, lon: 25, time: 120)
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04
Dimensions without coordinates: time
Data variables:
    Zeta     (time, lat, lon) float64 dask.array<chunksize=(1, 25, 25), meta=np.ndarray>

In [6]:
zeta_comp = Zeta.Zeta[0:25,:,:]

In [7]:
zeta_comp = zeta_comp.compute()

In [8]:
zeta_comp

<xarray.DataArray 'Zeta' (time: 25, lat: 25, lon: 25)>
array([[[-4.91475589e-08, -1.50649612e-07, -2.10216811e-07, ...,
         -2.11701959e-07, -2.44955913e-07, -2.89042987e-07],
        [-7.21115399e-08, -1.89708203e-07, -2.44534220e-07, ...,
         -1.00362136e-07, -1.20919864e-07, -1.49242865e-07],
        [-1.21302179e-07, -2.45345973e-07, -3.55424874e-07, ...,
         -3.98289117e-08,  6.10121305e-08,  2.85666488e-07],
        ...,
        [-1.22941358e-07, -1.02072050e-07,  6.22749994e-08, ...,
          2.99970004e-08, -9.49806491e-08, -1.69046885e-07],
        [-1.88184373e-07, -3.31688739e-07, -3.33620164e-07, ...,
         -2.47385543e-07, -3.26953256e-07, -2.98010349e-07],
        [-3.99708938e-07, -5.94364735e-07, -6.63619687e-07, ...,
         -5.03683850e-07, -4.63191299e-07, -3.56213746e-07]],

       [[-4.94020895e-08, -1.50054476e-07, -2.76412550e-07, ...,
         -5.30357340e-08, -6.71140228e-08, -1.31372673e-07],
        [-1.08695055e-07, -2.18964217e-07, -3.26239501e-07, ...,
         -2.31690862e-08, -9.95435645e-09, -4.63364849e-08],
        [-1.38918111e-07, -2.78560435e-07, -4.29322228e-07, ...,
         -7.44508171e-08,  1.71842984e-08,  1.08504636e-07],
...
        [ 3.42163867e-06,  1.22402298e-06,  3.91585843e-07, ...,
         -6.46765670e-07, -6.92065498e-07, -8.64839649e-07],
        [ 2.82634164e-06,  1.06311757e-06,  2.46472126e-07, ...,
         -5.79146558e-07, -7.37993332e-07, -9.95336450e-07],
        [ 2.32179832e-06,  9.55149972e-07,  4.21964558e-07, ...,
         -6.49727724e-07, -8.24255665e-07, -1.05362938e-06]],

       [[-9.41306610e-07, -8.55760049e-07, -7.19335389e-07, ...,
         -7.62708964e-07, -5.83417659e-07, -4.99024509e-07],
        [-6.81060214e-07, -7.27772260e-07, -7.61272190e-07, ...,
         -7.21529659e-07, -5.65586504e-07, -4.60871320e-07],
        [-4.79708604e-07, -5.69239887e-07, -7.05031141e-07, ...,
         -6.38241545e-07, -4.22009379e-07, -3.13891690e-07],
        ...,
        [ 4.64817776e-06,  7.62082709e-06,  8.08461482e-06, ...,
         -5.23979566e-07, -5.08368089e-07, -6.40208896e-07],
        [ 7.06136507e-06,  1.00265206e-05,  8.62469369e-06, ...,
         -5.88737635e-07, -6.01742045e-07, -7.73627164e-07],
        [ 8.21581125e-06,  9.68236509e-06,  6.85572923e-06, ...,
         -7.78685717e-07, -8.14435737e-07, -9.30083843e-07]]])
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04
Dimensions without coordinates: time

In [9]:
zeta

<xarray.DataArray 'Zeta' (time: 3, lat: 25, lon: 25)>
array([[[-4.91475589e-08, -1.50649612e-07, -2.10216811e-07, ...,
         -2.11701959e-07, -2.44955913e-07, -2.89042987e-07],
        [-7.21115399e-08, -1.89708203e-07, -2.44534220e-07, ...,
         -1.00362136e-07, -1.20919864e-07, -1.49242865e-07],
        [-1.21302179e-07, -2.45345973e-07, -3.55424874e-07, ...,
         -3.98289117e-08,  6.10121305e-08,  2.85666488e-07],
        ...,
        [-1.22941358e-07, -1.02072050e-07,  6.22749994e-08, ...,
          2.99970004e-08, -9.49806491e-08, -1.69046885e-07],
        [-1.88184373e-07, -3.31688739e-07, -3.33620164e-07, ...,
         -2.47385543e-07, -3.26953256e-07, -2.98010349e-07],
        [-3.99708938e-07, -5.94364735e-07, -6.63619687e-07, ...,
         -5.03683850e-07, -4.63191299e-07, -3.56213746e-07]],

       [[-4.94020895e-08, -1.50054476e-07, -2.76412550e-07, ...,
         -5.30357340e-08, -6.71140228e-08, -1.31372673e-07],
        [-1.08695055e-07, -2.18964217e-07, -3.26239501e-07, ...,
         -2.31690862e-08, -9.95435645e-09, -4.63364849e-08],
        [-1.38918111e-07, -2.78560435e-07, -4.29322228e-07, ...,
         -7.44508171e-08,  1.71842984e-08,  1.08504636e-07],
...
        [-4.13379411e-07, -3.08904134e-07, -6.65230786e-08, ...,
          2.06776861e-07,  1.49885395e-07,  4.69794195e-08],
        [-5.07708478e-07, -4.51105279e-07, -3.87404469e-07, ...,
         -1.41683813e-07, -1.44274281e-07, -1.42474903e-07],
        [-7.89154853e-07, -7.79717425e-07, -8.32743126e-07, ...,
         -4.56432645e-07, -3.68406688e-07, -2.61230838e-07]],

       [[ 1.79361592e-08, -1.82477095e-07, -2.82262732e-07, ...,
          4.70194017e-09, -1.78320043e-08, -9.22933481e-08],
        [ 5.53625146e-09, -1.13273948e-07, -2.62894105e-07, ...,
         -4.05224796e-08, -2.21194743e-08, -3.72433639e-08],
        [-8.76261730e-09, -9.59162065e-08, -3.09317358e-07, ...,
         -1.22887570e-07, -2.11336797e-08,  3.87214847e-08],
        ...,
        [-3.15557429e-07, -3.99210819e-07, -3.50115613e-07, ...,
         -2.30438701e-07,  1.14468968e-07,  2.91194993e-07],
        [-5.52618928e-07, -4.72011834e-07, -5.11834628e-07, ...,
         -4.73476177e-07, -1.74539224e-07,  2.27961543e-08],
        [-7.15045985e-07, -6.54628138e-07, -8.22477091e-07, ...,
         -7.43703595e-07, -4.31753449e-07, -1.72615060e-07]]])
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04
Dimensions without coordinates: time

In [11]:
np.array_equal(zeta_comp[0:3,:,:].values, zeta[0:3,:,:].values, equal_nan=True)

True

In [30]:
lat1 = 34
lat2 = 35
latinc = 0.04
lon1 = -65
lon2 = -64
loninc = 0.04
lat_out = np.arange(lat1,lat2,latinc)
lon_out = np.arange(lon1,lon2,loninc)
full_output = xr.DataArray(zeta_comp[0:1,:,:].values, dims=("time","lat","lon"), coords = {'lat':lat_out, 'lon':lon_out})

In [31]:
full_output

<xarray.DataArray (time: 1, lat: 25, lon: 25)>
array([[[-4.91475589e-08, -1.50649612e-07, -2.10216811e-07,
         -2.06930764e-07, -1.86090915e-07, -1.42634207e-07,
         -7.03767853e-08, -8.33918889e-08, -1.86243312e-07,
         -2.66890083e-07, -2.62170573e-07, -2.44070236e-07,
         -2.59792557e-07, -2.93968981e-07, -3.21566517e-07,
         -3.28951899e-07, -3.31479612e-07, -2.96808963e-07,
         -2.51390816e-07, -2.49595018e-07, -2.56040323e-07,
         -2.29789606e-07, -2.11701959e-07, -2.44955913e-07,
         -2.89042987e-07],
        [-7.21115399e-08, -1.89708203e-07, -2.44534220e-07,
         -2.24388174e-07, -2.41331804e-07, -2.33396150e-07,
         -1.31059352e-07, -7.51945919e-08, -1.42268419e-07,
         -2.40447974e-07, -2.81349259e-07, -3.19308811e-07,
         -3.77051720e-07, -4.15431742e-07, -4.38207962e-07,
         -4.62665241e-07, -4.59096384e-07, -3.68562894e-07,
         -2.73992185e-07, -2.54084796e-07, -2.36177186e-07,
         -1.55807115e-07, -1.00362136e-07, -1.20919864e-07,
         -1.49242865e-07],
        [-1.21302179e-07, -2.45345973e-07, -3.55424874e-07,
         -3.36888888e-07, -3.35164884e-07, -3.46931614e-07,
...
          1.13369850e-07,  2.99970004e-08, -9.49806491e-08,
         -1.69046885e-07],
        [-1.88184373e-07, -3.31688739e-07, -3.33620164e-07,
         -2.38464906e-07, -6.51074146e-08,  1.55439892e-07,
          1.16208668e-07, -2.62181317e-07, -6.13532507e-07,
         -6.71436453e-07, -4.93818504e-07, -2.12303377e-07,
         -2.47890348e-08, -5.72331267e-08, -3.71257954e-07,
         -7.71637076e-07, -9.20275056e-07, -7.32337071e-07,
         -3.75383792e-07, -1.59458438e-07, -1.21430872e-07,
         -1.50759135e-07, -2.47385543e-07, -3.26953256e-07,
         -2.98010349e-07],
        [-3.99708938e-07, -5.94364735e-07, -6.63619687e-07,
         -5.23623612e-07, -2.19993311e-07,  2.73704988e-08,
         -6.86528239e-08, -3.71730749e-07, -5.77460810e-07,
         -5.90619493e-07, -4.48780128e-07, -2.44112073e-07,
         -1.64098140e-07, -3.01125425e-07, -6.05631897e-07,
         -8.56667839e-07, -8.27764211e-07, -6.20577850e-07,
         -4.49654152e-07, -4.03163853e-07, -4.27477175e-07,
         -4.70863995e-07, -5.03683850e-07, -4.63191299e-07,
         -3.56213746e-07]]])
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04
Dimensions without coordinates: time

In [61]:
np.array_equal(zeta_comp[0:24,:,:].values, output[0:24,:,:].values, equal_nan=True)

True

In [33]:
full_output = xr.concat([full_output,zeta_comp[1:2,:,:]],'time')

In [34]:
np.array_equal(zeta_comp[0:2,:,:].values, full_output[0].values, equal_nan=True)

False

In [35]:
from timeline_MITgcm import timeline

In [58]:
y1 = 2020
y2 = 2020
m1 = 3
m2 = 3
d1 = 1
d2 = 2
h1 = 0
h2 = 0
M1 = 0
M2 = 0

lat1 = 34
lat2 = 35
latinc = 0.04
lon1 = -65
lon2 = -64
loninc = 0.04

level=0
ffilter=0
fsize=0
if (level==0):
  print('Entering MIT_xr_date_location')
  ########################################################
  # Same as MIT_xr but date and location are parameters
  # in a future update, this will require some errorhandling, especially when
  # you share this!
  ########################################################
  # date = np.arange(datetime(y1,m1,d1,h1,M1),datetime(y2,m2,d2,h2,M2),
  #                 timedelta(hours=1)).astype(datetime)
  # timedelta(hours=1) - pretty sure this means that there are 1 hour increments?
  initial_time = (str(y1) + '%02d' + '%02d' + '%02d' + '%02d') % (m1, d1,h1, M1)
  end_time = (str(y2) + '%02d' + '%02d' + '%02d' + '%02d') % (m2,d2,h2, M2)
  reference_time = '20200119213000'
  timedelta = 1 #hours
  rate = 3600 # sampling rate
  dt = 45 # seconds
  all_iters, date = timeline(initial_time, end_time, reference_time,timedelta,rate,dt)
  t = date.shape
  print('date')
  print(str(date) + '\n')
  print(str(all_iters)+ '\n')
  ##################################
  # Output grid
  ##################################
  print('setting location')
  lat_out = np.arange(lat1, lat2, latinc)
  lon_out = np.arange(lon1, lon2, loninc)
  #lat_out = np.arange(-90,90+0.04,0.04)
  #lon_out = np.arange(-180,180,0.04)
  print('location')
  ##################################
  # MIT iterations
  ##################################

  #iter0 = 0#120960
  delta_t=45 #45 second iterations 
  #delta = 3600/delta_t # iters
  nfiles = t[0]
  #all_iters = iter0 + delta*np.arange(nfiles)

  #### don't change this part
  if (VAR == 'DxTheta'):
    diro = '/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/Theta'
  elif (VAR == 'DyTheta'):
    diro = '/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/Theta'
  elif (VAR == 'Zeta'):
    diro = '/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/oceTAUX'
  elif (VAR == 'HAdv'):
    diro = '/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/Theta'
  else:
    diro = '/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/'+VAR+'/'
   
  ####
  print('Directory of files')
  print(diro)
  nx=2160
  GRIDDIR='/nobackupp2/estrobac/geos5/MITGRID/llc2160/'
  ####
  print('before mds')
  ds = open_mdsdataset(diro, grid_dir=GRIDDIR, iters=all_iters[0], 
                       geometry='llc', read_grid=True, 
                       default_dtype=np.dtype('>f4'),
                       delta_t=delta_t, ignore_unknown_vars=True, nx=nx)

  grid = xgcm.Grid(ds, periodic=False, face_connections=face_connections)
  print('grid xgcm.Grid')


  coords = ds.coords.to_dataset().reset_coords()
  msk=coords.hFacC.sel(k=0)
  msk=msk.where(msk>0,np.nan) 
  XC=coords.XC*msk
  YC=coords.YC*msk
  print('initialize mapping to GEOS grid')
  mapper = LLCMap_nea_split(YC.values, XC.values,lat_out,
                            lon_out,radius=10e3)


  ##################################
  # Creating folders
  ################################
  #make directory for the output

  ### change this part
  #prntout = '/nobackup/htorresg/air_sea/ocean-atmos/NCFILES/geosgcm_surf_tides_4km/'
  #prntout = pdirout #'/nobackup/amondal/NCData/20210629_TempHeterogeneity/'
  #####
  #dirout=prntout+VAR+"_"+str(level)
  #print('==== Folder to be created =======')
  #print(dirout)
  #if not os.path.exists(dirout):
      #os.makedirs(dirout)

    
  #################################
  # MIT iterations
  ################################
  output=xr.DataArray(np.zeros((nfiles,lat_out.shape[0],lon_out.shape[0])),
                      dims=("time","lat","lon"),
                      coords={'lat':lat_out,'lon':lon_out})
  output = output.rename(VAR)

  for i in range(0,(nfiles)):
    print(i)
    start = tm.time()
    print('open files')
    print(all_iters[i])

    ds = open_mdsdataset(diro, grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/', iters=all_iters[i], geometry='llc', read_grid=True, default_dtype=np.dtype('>f4'), delta_t=delta_t, ignore_unknown_vars=True, nx=nx)
    

    if VAR == 'V':
      #### change this part
      dirou='/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/U/'
      ####
      dsu = open_mdsdataset(dirou,
                      grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/',
                            iters=all_iters[i],geometry='llc',read_grid=True,
                            default_dtype=np.dtype('>f4'),delta_t=delta_t,
                            ignore_unknown_vars=True,nx=nx)
      ds1 = open_mdsdataset(GRIDDIR, iters=1, ignore_unknown_vars=True, geometry='llc', nx=nx)

      AngleCS=ds1['CS'];AngleSN=ds1['SN'];
      print('=== interp 2d ====')
      UV=grid.interp_2d_vector({'X': dsu['U'].isel(k=level), 'Y': ds['V'].isel(k=level)},boundary='fill')
      x=(UV['X']*AngleSN+UV['Y']*AngleCS)
      print('== done interp 2d ===')
      print('=== x interpolated  ==')
      print(x.shape)
    elif VAR == 'U':
      #### change this part
      dirov='/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/V/'
      ####
      dsv = open_mdsdataset(dirov,
                      grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/',
                            iters=all_iters[i],geometry='llc',read_grid=True,
                            default_dtype=np.dtype('>f4'),delta_t=delta_t,
                            ignore_unknown_vars=True,nx=nx)
      ds1 = open_mdsdataset(GRIDDIR, iters=1, ignore_unknown_vars=True, geometry='llc', nx=nx)  
      AngleCS=ds1['CS'];AngleSN=ds1['SN'];
      print('=== interp 2d ====')
      UV=grid.interp_2d_vector({'X': ds['U'].isel(k=level), 'Y': dsv['V'].isel(k=level)},boundary='fill')
      x=(UV['X']*AngleCS-UV['Y']*AngleSN)
      print('== done interp 2d ===')
      print('=== x interpolated  ==')
      print(x)
     
    elif VAR == 'oceTAUX':
      ### change this part
      dirov='/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/oceTAUY/'
      ###
      dsv = open_mdsdataset(dirov,
                      grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/',
                            iters=all_iters[i],geometry='llc',read_grid=True,
                            default_dtype=np.dtype('>f4'),delta_t=delta_t,
                            ignore_unknown_vars=True,nx=nx)
      AngleCS=dsv['CS'];AngleSN=dsv['SN'];
      print('=== interp 2d ====')
      UV=grid.interp_2d_vector({'X': ds['oceTAUX'], 'Y': dsv['oceTAUY']},boundary='fill')
      x=(UV['X']*AngleCS-UV['Y']*AngleSN)
      print('== done interp 2d ===')
      print('=== x interpolated  ==')
      print(np.nanmean(x))
    elif VAR == 'oceTAUY':
	###### change this part
      dirou='/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/oceTAUX/'
	##### 
      dsu = open_mdsdataset(dirou,
                      grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/',
                            iters=all_iters[i],geometry='llc',read_grid=True,
                            default_dtype=np.dtype('>f4'),delta_t=delta_t,
                            ignore_unknown_vars=True,nx=nx)
      AngleCS=dsu['CS'];AngleSN=dsu['SN'];
      print('=== interp 2d ====')
      UV=grid.interp_2d_vector({'X': dsu['oceTAUX'], 'Y': ds['oceTAUY']},boundary='fill')
      x=(UV['X']*AngleSN+UV['Y']*AngleCS)
      print('== done interp 2d ===')
      print('=== x interpolated  ==')
      print(np.nanmean(x))
    elif VAR == 'Zeta':
      ### change this part
      dirov='/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/oceTAUY/'
      ###
      dsv = open_mdsdataset(dirov,
                      grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/',
                            iters=all_iters[i],geometry='llc',read_grid=True,
                            default_dtype=np.dtype('>f4'),delta_t=delta_t,
                            ignore_unknown_vars=True,nx=nx)
      grid = xgcm.Grid(ds)
      zeta = (-grid.diff(ds['oceTAUX']*ds.dxC,'Y') + grid.diff(dsv['oceTAUY']*ds.dyC,'X')) / ds.rAz
      x = grid.interp(grid.interp(zeta,axis='X', to='center'), axis='Y',to='center')
      print('=== x interpolated  ==')
      print(np.nanmean(x))
  
    elif VAR == 'W':
      x=grid.interp(ds['W'],'Z',to='center',boundary='fill').isel(k=level)
    elif VAR == 'Eta':
      x=ds[VAR]
    elif VAR == 'KPPhbl':
      x=ds[VAR]
    elif VAR == 'Theta':
      x=ds[VAR].isel(k=level)
    elif VAR == 'Salt':
      x=ds[VAR].isel(k=level)
    elif VAR == 'oceQnet':
      x=ds[VAR]
    elif VAR == 'oceQsw':
      x=ds[VAR]
    elif VAR == 'DyTheta':
      dgrid = xgcm.Grid(ds)
      DxTheta = dgrid.diff(ds['Theta'].isel(k=level),axis='X',boundary='fill') / ds.dxC
      DyTheta = dgrid.diff(ds['Theta'].isel(k=level),axis='Y',boundary='fill') / ds.dyC
      ds1 = open_mdsdataset(GRIDDIR, iters=1, ignore_unknown_vars=True,geometry='llc', nx=nx)
      AngleCS=ds1['CS'];AngleSN=ds1['SN'];
      UV=grid.interp_2d_vector({'X':DxTheta, 'Y':DyTheta},boundary='fill')
      x=(UV['X']*AngleSN+UV['Y']*AngleCS)
    elif VAR =='DxTheta':
      dgrid = xgcm.Grid(ds)
      DxTheta = dgrid.diff(ds['Theta'].isel(k=level),axis='X',boundary='fill') / ds.dxC
      DyTheta = dgrid.diff(ds['Theta'].isel(k=level),axis='Y',boundary='fill') / ds.dyC
      ds1 = open_mdsdataset(GRIDDIR, iters=1, ignore_unknown_vars=True,geometry='llc', nx=nx)
      AngleCS=ds1['CS'];AngleSN=ds1['SN'];
      UV=grid.interp_2d_vector({'X':DxTheta, 'Y':DyTheta},boundary='fill')
      x=(UV['X']*AngleCS-UV['Y']*AngleSN)
    elif VAR =='HAdv':
      dirou='/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/U/'
      ####
      dsu = open_mdsdataset(dirou,
                      grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/',
                            iters=all_iters[i],geometry='llc',read_grid=True,
                            default_dtype=np.dtype('>f4'),delta_t=delta_t,
                            ignore_unknown_vars=True,nx=nx)
      dirov='/nobackupp11/dmenemen/DYAMOND/c1440_llc2160/mit_output/V/'
      ###
      dsv = open_mdsdataset(dirov,
                      grid_dir='/nobackupp2/estrobac/geos5/MITGRID/llc2160/',
                            iters=all_iters[i],geometry='llc',read_grid=True,
                            default_dtype=np.dtype('>f4'),delta_t=delta_t,
                            ignore_unknown_vars=True,nx=nx)
      dgrid = xgcm.Grid(ds)
      DxTheta = dgrid.diff(ds['Theta'].isel(k=level),axis='X',boundary='fill') / ds.dxC
      DyTheta = dgrid.diff(ds['Theta'].isel(k=level),axis='Y',boundary='fill') / ds.dyC
      xadv = dsu['U'].isel(k=level)*DxTheta
      yadv = dsv['V'].isel(k=level)*DyTheta
      xadv_interp = dgrid.interp(xadv,axis='X',to='center')
      yadv_interp = dgrid.interp(yadv,axis='Y',to='center')
      x = xadv_interp + yadv_interp
    else:
      print('not yet implemented')


    ##################################################
    ##### Mapping X to new grid
    print('map field') 
    TMP=xr.DataArray(mapper(x.values))
    print('mapped')

    if ffilter==1:
      print('apply filter')
      output[i] = TMP - dask_ndfilters.generic_filter(da.from_array(TMP, \
               chunks=[131,960]), \
               function=np.nanmean, \
               size=fsize, \
               mode='wrap', \
               origin=0).compute()
    else:
      output[i] = TMP
    
    del TMP
    

    print('finished day %02d'%i)
    end = tm.time()
    print(end - start)
  
    """
    if (i==0):
      full_output = output
      print('Did the code go to the i=0 case?')
      #print(full_output.values)
    else:
      print('How about the append case?')  
      full_output = xr.concat([full_output, output],'time')
    """

Entering MIT_xr_date_location
date
[datetime.datetime(2020, 3, 1, 0, 0) datetime.datetime(2020, 3, 1, 1, 0)
 datetime.datetime(2020, 3, 1, 2, 0) datetime.datetime(2020, 3, 1, 3, 0)
 datetime.datetime(2020, 3, 1, 4, 0) datetime.datetime(2020, 3, 1, 5, 0)
 datetime.datetime(2020, 3, 1, 6, 0) datetime.datetime(2020, 3, 1, 7, 0)
 datetime.datetime(2020, 3, 1, 8, 0) datetime.datetime(2020, 3, 1, 9, 0)
 datetime.datetime(2020, 3, 1, 10, 0) datetime.datetime(2020, 3, 1, 11, 0)
 datetime.datetime(2020, 3, 1, 12, 0) datetime.datetime(2020, 3, 1, 13, 0)
 datetime.datetime(2020, 3, 1, 14, 0) datetime.datetime(2020, 3, 1, 15, 0)
 datetime.datetime(2020, 3, 1, 16, 0) datetime.datetime(2020, 3, 1, 17, 0)
 datetime.datetime(2020, 3, 1, 18, 0) datetime.datetime(2020, 3, 1, 19, 0)
 datetime.datetime(2020, 3, 1, 20, 0) datetime.datetime(2020, 3, 1, 21, 0)
 datetime.datetime(2020, 3, 1, 22, 0) datetime.datetime(2020, 3, 1, 23, 0)
 datetime.datetime(2020, 3, 2, 0, 0)]

[78880. 78960. 79040. 79120. 79200. 

In [53]:
output[0]

<xarray.DataArray 'Zeta' (lat: 25, lon: 25)>
array([[-4.91475589e-08, -1.50649612e-07, -2.10216811e-07,
        -2.06930764e-07, -1.86090915e-07, -1.42634207e-07,
        -7.03767853e-08, -8.33918889e-08, -1.86243312e-07,
        -2.66890083e-07, -2.62170573e-07, -2.44070236e-07,
        -2.59792557e-07, -2.93968981e-07, -3.21566517e-07,
        -3.28951899e-07, -3.31479612e-07, -2.96808963e-07,
        -2.51390816e-07, -2.49595018e-07, -2.56040323e-07,
        -2.29789606e-07, -2.11701959e-07, -2.44955913e-07,
        -2.89042987e-07],
       [-7.21115399e-08, -1.89708203e-07, -2.44534220e-07,
        -2.24388174e-07, -2.41331804e-07, -2.33396150e-07,
        -1.31059352e-07, -7.51945919e-08, -1.42268419e-07,
        -2.40447974e-07, -2.81349259e-07, -3.19308811e-07,
        -3.77051720e-07, -4.15431742e-07, -4.38207962e-07,
        -4.62665241e-07, -4.59096384e-07, -3.68562894e-07,
        -2.73992185e-07, -2.54084796e-07, -2.36177186e-07,
        -1.55807115e-07, -1.00362136e-07, -1.20919864e-07,
        -1.49242865e-07],
       [-1.21302179e-07, -2.45345973e-07, -3.55424874e-07,
        -3.36888888e-07, -3.35164884e-07, -3.46931614e-07,
...
         1.13369850e-07,  2.99970004e-08, -9.49806491e-08,
        -1.69046885e-07],
       [-1.88184373e-07, -3.31688739e-07, -3.33620164e-07,
        -2.38464906e-07, -6.51074146e-08,  1.55439892e-07,
         1.16208668e-07, -2.62181317e-07, -6.13532507e-07,
        -6.71436453e-07, -4.93818504e-07, -2.12303377e-07,
        -2.47890348e-08, -5.72331267e-08, -3.71257954e-07,
        -7.71637076e-07, -9.20275056e-07, -7.32337071e-07,
        -3.75383792e-07, -1.59458438e-07, -1.21430872e-07,
        -1.50759135e-07, -2.47385543e-07, -3.26953256e-07,
        -2.98010349e-07],
       [-3.99708938e-07, -5.94364735e-07, -6.63619687e-07,
        -5.23623612e-07, -2.19993311e-07,  2.73704988e-08,
        -6.86528239e-08, -3.71730749e-07, -5.77460810e-07,
        -5.90619493e-07, -4.48780128e-07, -2.44112073e-07,
        -1.64098140e-07, -3.01125425e-07, -6.05631897e-07,
        -8.56667839e-07, -8.27764211e-07, -6.20577850e-07,
        -4.49654152e-07, -4.03163853e-07, -4.27477175e-07,
        -4.70863995e-07, -5.03683850e-07, -4.63191299e-07,
        -3.56213746e-07]])
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04

In [38]:
full_output[1]

<xarray.DataArray 'Zeta' (lat: 25, lon: 25)>
array([[-4.94020895e-08, -1.50054476e-07, -2.76412550e-07,
        -3.68065287e-07, -3.69701183e-07, -2.64531337e-07,
        -1.60504641e-07, -1.36319898e-07, -1.85542618e-07,
        -2.33011647e-07, -2.32161653e-07, -2.03160724e-07,
        -1.86638687e-07, -2.01519356e-07, -2.34617914e-07,
        -2.55768356e-07, -2.72301179e-07, -2.89509472e-07,
        -2.81984768e-07, -2.51690381e-07, -2.25731483e-07,
        -1.47464888e-07, -5.30357340e-08, -6.71140228e-08,
        -1.31372673e-07],
       [-1.08695055e-07, -2.18964217e-07, -3.26239501e-07,
        -3.64349944e-07, -3.68857030e-07, -3.14659530e-07,
        -2.09530299e-07, -1.26589399e-07, -1.36408062e-07,
        -1.94986029e-07, -2.29836729e-07, -2.44970806e-07,
        -2.59450587e-07, -2.77175133e-07, -3.00140272e-07,
        -3.51190693e-07, -3.98026657e-07, -3.79628034e-07,
        -3.42976648e-07, -3.16624778e-07, -2.66787197e-07,
        -1.44101364e-07, -2.31690862e-08, -9.95435645e-09,
        -4.63364849e-08],
       [-1.38918111e-07, -2.78560435e-07, -4.29322228e-07,
        -4.29477751e-07, -3.84230106e-07, -3.65706967e-07,
...
         3.73826481e-09,  2.06776861e-07,  1.49885395e-07,
         4.69794195e-08],
       [-5.07708478e-07, -4.51105279e-07, -3.87404469e-07,
        -2.02158816e-07, -4.69061234e-08,  8.98523496e-08,
         2.42966081e-07,  2.26407806e-07, -2.04335322e-08,
        -2.70634871e-07, -4.98236943e-07, -5.45868488e-07,
        -3.74152165e-07, -2.44667262e-07, -1.51921114e-07,
        -1.91674530e-07, -3.96943648e-07, -6.70908776e-07,
        -8.44466172e-07, -7.41245003e-07, -5.06566835e-07,
        -2.72463097e-07, -1.41683813e-07, -1.44274281e-07,
        -1.42474903e-07],
       [-7.89154853e-07, -7.79717425e-07, -8.32743126e-07,
        -7.37640221e-07, -5.15201009e-07, -2.22328623e-07,
         3.24024043e-08,  6.60032669e-08, -7.08348651e-08,
        -1.62132878e-07, -3.05353467e-07, -4.11889062e-07,
        -3.93676629e-07, -4.17163392e-07, -3.91519933e-07,
        -3.78377592e-07, -4.56222381e-07, -6.21495133e-07,
        -7.97979681e-07, -7.99955501e-07, -6.85394298e-07,
        -5.60834678e-07, -4.56432645e-07, -3.68406688e-07,
        -2.61230838e-07]])
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04

In [47]:
full_output[1]

<xarray.DataArray 'Zeta' (lat: 25, lon: 25)>
array([[-4.94020895e-08, -1.50054476e-07, -2.76412550e-07,
        -3.68065287e-07, -3.69701183e-07, -2.64531337e-07,
        -1.60504641e-07, -1.36319898e-07, -1.85542618e-07,
        -2.33011647e-07, -2.32161653e-07, -2.03160724e-07,
        -1.86638687e-07, -2.01519356e-07, -2.34617914e-07,
        -2.55768356e-07, -2.72301179e-07, -2.89509472e-07,
        -2.81984768e-07, -2.51690381e-07, -2.25731483e-07,
        -1.47464888e-07, -5.30357340e-08, -6.71140228e-08,
        -1.31372673e-07],
       [-1.08695055e-07, -2.18964217e-07, -3.26239501e-07,
        -3.64349944e-07, -3.68857030e-07, -3.14659530e-07,
        -2.09530299e-07, -1.26589399e-07, -1.36408062e-07,
        -1.94986029e-07, -2.29836729e-07, -2.44970806e-07,
        -2.59450587e-07, -2.77175133e-07, -3.00140272e-07,
        -3.51190693e-07, -3.98026657e-07, -3.79628034e-07,
        -3.42976648e-07, -3.16624778e-07, -2.66787197e-07,
        -1.44101364e-07, -2.31690862e-08, -9.95435645e-09,
        -4.63364849e-08],
       [-1.38918111e-07, -2.78560435e-07, -4.29322228e-07,
        -4.29477751e-07, -3.84230106e-07, -3.65706967e-07,
...
         3.73826481e-09,  2.06776861e-07,  1.49885395e-07,
         4.69794195e-08],
       [-5.07708478e-07, -4.51105279e-07, -3.87404469e-07,
        -2.02158816e-07, -4.69061234e-08,  8.98523496e-08,
         2.42966081e-07,  2.26407806e-07, -2.04335322e-08,
        -2.70634871e-07, -4.98236943e-07, -5.45868488e-07,
        -3.74152165e-07, -2.44667262e-07, -1.51921114e-07,
        -1.91674530e-07, -3.96943648e-07, -6.70908776e-07,
        -8.44466172e-07, -7.41245003e-07, -5.06566835e-07,
        -2.72463097e-07, -1.41683813e-07, -1.44274281e-07,
        -1.42474903e-07],
       [-7.89154853e-07, -7.79717425e-07, -8.32743126e-07,
        -7.37640221e-07, -5.15201009e-07, -2.22328623e-07,
         3.24024043e-08,  6.60032669e-08, -7.08348651e-08,
        -1.62132878e-07, -3.05353467e-07, -4.11889062e-07,
        -3.93676629e-07, -4.17163392e-07, -3.91519933e-07,
        -3.78377592e-07, -4.56222381e-07, -6.21495133e-07,
        -7.97979681e-07, -7.99955501e-07, -6.85394298e-07,
        -5.60834678e-07, -4.56432645e-07, -3.68406688e-07,
        -2.61230838e-07]])
Coordinates:
  * lat      (lat) float64 34.0 34.04 34.08 34.12 ... 34.84 34.88 34.92 34.96
  * lon      (lon) float64 -65.0 -64.96 -64.92 -64.88 ... -64.12 -64.08 -64.04

In [39]:
np.array_equal(full_output[0].values, full_output[1].values, equal_nan=True)

True